name: csv2html
description: Converts a CSV file into pretty printed HTML
version: 1.0.0
homepage: https://github.com/qcif/csv2html

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  args: ^1.5.1
  csv: ^4.1.0
  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
